### ISSUE TITLE
Vagrant post-processor doesn't work properly with DigitalOcean

### ISSUE THREAD

**Issue by roll** [mitchellh/packer#1757]
Without post-processor it works fine. 
With post-processor something weird goes on:
- snapshot has been deleted despite `keep_input_artifact`
- error: "Post-processor failed: Poorly formatted artifact ID"

People here #1639 blame 3d6865fafc394e888dea07abd7f2afcc524ecee7

```
>>> packer version
Packer v0.7.5
```
```
>>> cat box.json
{
  "variables": {
    "do_token": "{{ env `DIGITALOCEAN_API_TOKEN`}}"
  },
  "builders": [{
    "type": "digitalocean",
    "api_token": "{{user `do_token`}}",
    "image": "ubuntu-14-04-x64",
    "region": "ams3",
    "size": "512mb"
  }],
  "post-processors": [{
  	"type": "vagrant",
  	"keep_input_artifact": true 
  }]
}
```

```
>>> packer build box.json
...
2014/12/14 12:26:49 ui: ==> digitalocean: Running post-processor: vagrant
==> digitalocean: Running post-processor: vagrant
2014/12/14 12:26:49 ui: ==> digitalocean (vagrant): Creating Vagrant box for 'digitalocean' provider
==> digitalocean (vagrant): Creating Vagrant box for 'digitalocean' provider
2014/12/14 12:26:49 Deleting original artifact for build 'digitalocean'
2014/12/14 12:26:49 packer-builder-digitalocean: 2014/12/14 12:26:49 Destroying image: 9012200 (packer-1418549026)
2014/12/14 12:26:49 packer-builder-digitalocean: 2014/12/14 12:26:49 sending new request to digitalocean: https://api.digitalocean.com/v2/images/9012200 buffer:
2014/12/14 12:26:50 ui error: Build 'digitalocean' errored: 1 error(s) occurred:

* Post-processor failed: Poorly formatted artifact ID: 9012200
2014/12/14 12:26:50 Builds completed. Waiting on interrupt barrier...
2014/12/14 12:26:50 machine readable: error-count []string{"1"}
2014/12/14 12:26:50 ui error: 
==> Some builds didn't complete successfully and had errors:
2014/12/14 12:26:50 machine readable: digitalocean,error []string{"1 error(s) occurred:\n\n* Post-processor failed: Poorly formatted artifact ID: 9012200"}
2014/12/14 12:26:50 ui error: --> digitalocean: 1 error(s) occurred:

* Post-processor failed: Poorly formatted artifact ID: 9012200
2014/12/14 12:26:50 ui: 
==> Builds finished but no artifacts were created.
2014/12/14 12:26:50 waiting for all plugin processes to complete...
Build 'digitalocean' errored: 1 error(s) occurred:

* Post-processor failed: Poorly formatted artifact ID: 9012200

==> Some builds didn't complete successfully and had errors:
--> digitalocean: 1 error(s) occurred:

* Post-processor failed: Poorly formatted artifact ID: 9012200

==> Builds finished but no artifacts were created.
2014/12/14 12:26:50 /opt/packer/packer-builder-digitalocean: plugin process exited
2014/12/14 12:26:50 /opt/packer/packer-post-processor-vagrant: plugin process exited
```

**Comment by sethvargo** [comment]
I believe this was fixed with https://github.com/mitchellh/packer/commit/4f22fd25f5a88057e9adf66f7454899c9519ecfe.

**Comment by arosenhagen** [comment]
unfortunately this is still an issue. I keep getting `Post-processor failed: Poorly formatted artifact ID: 11316684` with current master (b49d74d9990c56eba0b967fd952347d83cd68488)

**Comment by paolodina** [comment]
@arosenhagen confirm, same here.

**Comment by mcrypt** [comment]
+1 same issue.
