### ISSUE TITLE
Can't get `include` to work with packer push

### ISSUE THREAD

**Issue by henrikhodne** [mitchellh/packer#1822]
When I have a push config like this:

``` JSON
{
  "push": {
    "name": "foo/bar",
    "include": [
      "template.json",
      "scripts/*"
    ]
  }
}
```

Also, a provisioner like this:

``` JSON
{
  "type": "shell",
  "script": "scripts/install.sh"
}
```

I'd expect the install.sh file to get uploaded, but it seems that doesn't happen, as I get this in the log on Atlas:

```
1 error(s) occurred:

* Bad script 'scripts/install.sh': stat scripts/install.sh: no such file or directory
```

I also tried to add `"vcs": false` to the push config and I tried adding the files to Git, but neither made a difference.

Output with `PACKER_LOG=1`: https://gist.github.com/henrikhodne/8400933068a16c33bc80

/cc @sethvargo @mitchellh

**Comment by KFishner** [comment]
We just added some more documentation to clarify this process:
https://atlas.hashicorp.com/help/FAQ/packer

You need to make sure you move the scripts from Atlas and to the instance you are provisioning. Here are some examples to help as well:
https://github.com/hashicorp/atlas-examples

**Comment by henrikhodne** [comment]
The [shell provisioner docs](https://packer.io/docs/provisioners/shell.html) should probably be updated too then, since it says that it uploads the file for you:

> The path to a script to *upload* and execute in the machine. This path can be absolute or relative. If it is relative, it is relative to the working directory when Packer is executed.

(emphasis mine)

**Comment by sethvargo** [comment]
@KFishner ^

**Comment by KFishner** [comment]
These are actually separate issues, your use case of `Bad script 'scripts/install.sh': stat scripts/install.sh: no such file or directory` should work properly. Can you send the tree of the directory where you're Packer pushing from?

**Comment by henrikhodne** [comment]
Sorry for the late response. The tree looks something like this:

```
.
├── scripts
│   └── install.sh
└── template.json
```

**Comment by henrikhodne** [comment]
By the way, if I remove the `include` part of the push configuration, everything works great. I tried both of these:

```
"include": [ "scripts/*", "template.json" ]
```

```
"include": [ "scripts/install.sh", "template.json" ]
```

**Comment by KFishner** [comment]
sorry for the late response here - this should be fixed with: https://github.com/hashicorp/atlas-go/pull/32

**Comment by call-a3** [comment]
I'm still having a problem with this. When I `packer push`, the atlas build still errors with 'no such file or directory'. I tried vcs:false, with and without base_dir, with and without include (all combinations of base_dir and include) and finally vcs:true with and without include. Each time include using relative paths, basedir both relative and absolute path (using windows path notation and cygwin path notation)

**Comment by KFishner** [comment]
This _should_ be fixed in master:
https://github.com/hashicorp/atlas-go/pull/38

You can either build from master or wait for the next Packer release, which is coming very soon!
