### ISSUE TITLE
vmx_data_post not working with vmware-iso builder

### ISSUE THREAD

**Issue by trodemaster** [mitchellh/packer#2026]
In troubleshooting why the installer .iso was not dismounted I attempted to use vmx_data_post. What I found is that vmx_data_post is not working. I'm using Fusion 7.1.1, Packer 0.7.5 and OS X 10.10.2. I believe that this has been broken for a while and not OS X specific as I have seen the issue with workstation 11 on ubuntu 14. I now have a use case for vmx_data_post so here is the bug. 

Debug log from a build
https://gist.github.com/trodemaster/e647898efa786dea1918

template.json from this build
https://gist.github.com/trodemaster/8353e5ea4eb1194955c9

result .vmx
https://gist.github.com/trodemaster/d8a8c4c1ffbb0b62b14b

Reproduction should be fairly straight forward. Take a known good template and add vmx_data_post to it. Run the build and observe if the vmx result matches. In my case the installer .iso remains mounted as well. 

I suspect that the .vmx file is still locked in the filesystem even after the .vmx.lck file is removed. Might need another test for checking writability of the .vmx file.

**Comment by trodemaster** [comment]
May be related to https://github.com/mitchellh/packer/pull/903

**Comment by bluemarble** [comment]
This seems to be the same problem as [#1151](https://github.com/mitchellh/packer/issues/1151), which documents my experience with .iso files remaining mounted after the post processor runs.

I also have the problem where vmx_data_post changes are not reflected in the post processed .vmx.

I have found a workaround for both these problems, that works on Yosemite:  Quit VMware Fusion before running a packer build.

**Comment by mitchellh** [comment]
I believe this is fixed, I can't repro it anymore. Please let me know if Im' wrong.

**Comment by trodemaster** [comment]
I'm still having the issue with 0.7.5 release. Should I test a build from source? Do your vms build with the VMware GUI running? That is how I'm doing it and could contribute.

**Comment by dragon788** [comment]
@trodemaster When you say you "build with the GUI running" do you mean you have other VMs running or that you allow Packer to open a GUI and you watch the progress without interacting?

**Comment by trodemaster** [comment]
I'm let packer show the GUI with "headless": false

**Comment by dragon788** [comment]
@trodemaster do you also have the vnc remote display settings persisting, and does it behave different if you do a headless = true?

**Comment by aspring** [comment]
I originally reported the issue in #903 and have been patching each release with the following to get a build that works for me, as I hit this issue every time.

https://github.com/aspring/packer/commit/3c4b11600bd70bf78862decf95dd8bee0ea0e853
