### ISSUE TITLE
ssh_key_path is still required for VirtualBox and Parallels

### ISSUE THREAD

**Issue by jamesbishopp** [mitchellh/packer#2428]
Ran into an issue when attempting to create a VirtualBox image from a CoreOS ISO.  I specified the `ssh_private_key_file` as specified in the documentation but it was not being used when packer attempted to connect to the instance via SSH.  After looking at the packer source, I noticed that the virtualbox builder was only using the `ssh_private_key_file` configuration if `ssh_key_path` was also set (turns out only `ssh_key_path` is required). The image was created successfully once I set `ssh_key_path` to the same value as `ssh_private_key_file` (removing `ssh_private_key_file` also created the image).

* `builder/virtualbox/common/ssh_config.go:18` indicates that `SSHKeyPath` is deprecated.
* `builder/virtualbox/common/ssh_config.go:35` sets `SSHPrivateKey` to the value of `SSHKeyPath`
* `builder/virtualbox/common/ssh.go:27` checks if the `SSHKeyPath` is not an empty string and only then uses `SSHPrivateKey` as an authentication method.

Possible quick hack/fix?:
```patch
diff --git a/builder/virtualbox/common/ssh_config.go b/builder/virtualbox/common/ssh_config.go
index 8997c58..771d432 100644
--- a/builder/virtualbox/common/ssh_config.go
+++ b/builder/virtualbox/common/ssh_config.go
@@ -31,7 +31,9 @@ func (c *SSHConfig) Prepare(ctx *interpolate.Context) []error {
 	}
 
 	// TODO: backwards compatibility, write fixer instead
-	if c.SSHKeyPath != "" {
+	if c.SSHPrivateKey != "" {
+		c.Comm.SSHKeyPath = c.Comm.SSHPrivateKey
+	} else if c.SSHKeyPath != "" {
 		c.Comm.SSHPrivateKey = c.SSHKeyPath
 	}
 	if c.SSHWaitTimeout != 0 {

```

Other builders:
* qemu & vmware: only support `SSHPrivateKey` even though it still specifies `SSHKeyPath` as a valid config
* parallels: same issue as virtualbox

It doesn't look like it is a ton of work to remove `SSHKeyPath` and perhaps someone is already working on it so the hack/fix above would not be necessary or desired.  The only scary part seems to be that there are a number of tests that check `SSHKeyPath` that would need to be evaluted. At first look those tests don't seem to be overly complex and in most cases `SSHKeyPath` can just be replaced with `SSHPrivateKey`.

**Comment by t2d** [comment]
very unfortunate to run into this as a starter

**Comment by rickard-von-essen** [comment]
Closing, this was fixed in #2435. Released in `v0.9.0`

@t2d Upgrade

**Comment by t2d** [comment]
@rickard-von-essen I'm using 0.10.0. The problem is still present

**Comment by rickard-von-essen** [comment]
@t2d OK, open a new issue and fill in the details in the template.
