### ISSUE TITLE
communicator:none causes VirtualBox Error

### ISSUE THREAD

**Issue by aneeshusa** [mitchellh/packer#2772]
When using communicator:none with VirtualBox, packer will error out when trying to start the VM and the reported error from VirtualBox is empty. Running in -debug mode and manually starting the VM at that point works, and using the ssh communicator instead works. Additionally, I have VT-X enabled (#2063), and it seems communicator:none has other issues (#2749), so it appears the problem is due to communicator:none.

Minimal reproduction template:

``` json
{
  "builders": [
    {
      "type": "virtualbox-iso",
      "iso_url": "http://mirror.cc.columbia.edu/pub/linux/archlinux/iso/2015.09.01/archlinux-2015.09.01-dual.iso",
      "iso_checksum": "4eb065d1b7639846703422a30c622eae0a558622",
      "iso_checksum_type": "sha1",
      "guest_additions_mode": "disable",
      "communicator": "none"
    }
  ],
  "provisioners": [],
  "post-processors": []
}
```

Removing communicator:none and adding an ssh_username and ssh_password fixes the error when packer attempts to start the VM.

**Comment by rickard-von-essen** [comment]
Could you share the error you are experiencing?

**Comment by aneeshusa** [comment]
When attempting to start the VM, there is an empty VBoxManage error as in #2063, and the build fails:

```sh
==> virtualbox-iso: Downloading or copying ISO
    virtualbox-iso: Downloading or copying: http://mirror.cc.columbia.edu/pub/linux/archlinux/iso/2015.09.01/archlinux-2015.09.01-dual.iso
==> virtualbox-iso: Creating virtual machine...
==> virtualbox-iso: Creating hard drive...
==> virtualbox-iso: Creating forwarded port mapping for SSH (host port 3948)
==> virtualbox-iso: Starting the virtual machine...
==> virtualbox-iso: Error starting VM: VBoxManage error:
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Error starting VM: VBoxManage error:

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Error starting VM: VBoxManage error: 

==> Builds finished but no artifacts were created.
```

Setting the PACKER_LOG variable and -debug mode don't provide any other information about the error, but removing "communicator": "none" and providing an ssh_username and ssh_password in the template fix the problem.

**Comment by rickard-von-essen** [comment]
Duplicates #2736

**Comment by rickard-von-essen** [comment]
Ok let's keep this open to track this issue for VirtualBox.

**Comment by cbednarski** [comment]
I think this is fixed thanks to https://github.com/mitchellh/packer/pull/2848 but will verify before closing.

**Comment by aneeshusa** [comment]
I'd also like to verify this fixes my original issue, I should be able to try it out today or tomorrow.

**Comment by aneeshusa** [comment]
I just tested with Packer built from latest git sources and I'm still getting the same error. (I also tested with the ssh communicator, which still works.)

**Comment by tylert** [comment]
Related to #3304.

**Comment by synthead** [comment]
Have you guys found a workaround for this?

**Comment by mwhooker** [comment]
I know this was earlier, but it's a dupe of #3618. Tracking fix in #3619
