### ISSUE TITLE
Docker builder hanging

### ISSUE THREAD

**Issue by cbroglie** [mitchellh/packer#2981]
The root cause of this is errors on my side, but the issue with packer is that it's failing to detect that commands have failed and is hanging.

Here is the output up to where it hangs:
```
$ PACKER_LOG=1 packer build docker.json
2015/12/04 18:00:36 [INFO] Packer version: 0.8.6  f8f7b7a34c1be06058f5aca23a51247db12cdbc5+CHANGES
2015/12/04 18:00:36 Packer Target OS/Arch: darwin amd64
2015/12/04 18:00:36 Built with Go Version: go1.5
2015/12/04 18:00:36 [DEBUG] Discovered plugin: amazon-chroot = /usr/local/bin/packer-builder-amazon-chroot
2015/12/04 18:00:36 [DEBUG] Discovered plugin: amazon-ebs = /usr/local/bin/packer-builder-amazon-ebs
2015/12/04 18:00:36 [DEBUG] Discovered plugin: amazon-instance = /usr/local/bin/packer-builder-amazon-instance
2015/12/04 18:00:36 [DEBUG] Discovered plugin: digitalocean = /usr/local/bin/packer-builder-digitalocean
2015/12/04 18:00:36 [DEBUG] Discovered plugin: docker = /usr/local/bin/packer-builder-docker
2015/12/04 18:00:36 [DEBUG] Discovered plugin: file = /usr/local/bin/packer-builder-file
2015/12/04 18:00:36 [DEBUG] Discovered plugin: googlecompute = /usr/local/bin/packer-builder-googlecompute
2015/12/04 18:00:36 [DEBUG] Discovered plugin: null = /usr/local/bin/packer-builder-null
2015/12/04 18:00:36 [DEBUG] Discovered plugin: openstack = /usr/local/bin/packer-builder-openstack
2015/12/04 18:00:36 [DEBUG] Discovered plugin: parallels-iso = /usr/local/bin/packer-builder-parallels-iso
2015/12/04 18:00:36 [DEBUG] Discovered plugin: parallels-pvm = /usr/local/bin/packer-builder-parallels-pvm
2015/12/04 18:00:36 [DEBUG] Discovered plugin: qemu = /usr/local/bin/packer-builder-qemu
2015/12/04 18:00:36 [DEBUG] Discovered plugin: virtualbox-iso = /usr/local/bin/packer-builder-virtualbox-iso
2015/12/04 18:00:36 [DEBUG] Discovered plugin: virtualbox-ovf = /usr/local/bin/packer-builder-virtualbox-ovf
2015/12/04 18:00:36 [DEBUG] Discovered plugin: vmware-iso = /usr/local/bin/packer-builder-vmware-iso
2015/12/04 18:00:36 [DEBUG] Discovered plugin: vmware-vmx = /usr/local/bin/packer-builder-vmware-vmx
2015/12/04 18:00:36 [DEBUG] Discovered plugin: artifice = /usr/local/bin/packer-post-processor-artifice
2015/12/04 18:00:36 [DEBUG] Discovered plugin: atlas = /usr/local/bin/packer-post-processor-atlas
2015/12/04 18:00:36 [DEBUG] Discovered plugin: compress = /usr/local/bin/packer-post-processor-compress
2015/12/04 18:00:36 [DEBUG] Discovered plugin: docker-import = /usr/local/bin/packer-post-processor-docker-import
2015/12/04 18:00:36 [DEBUG] Discovered plugin: docker-push = /usr/local/bin/packer-post-processor-docker-push
2015/12/04 18:00:36 [DEBUG] Discovered plugin: docker-save = /usr/local/bin/packer-post-processor-docker-save
2015/12/04 18:00:36 [DEBUG] Discovered plugin: docker-tag = /usr/local/bin/packer-post-processor-docker-tag
2015/12/04 18:00:36 [DEBUG] Discovered plugin: vagrant = /usr/local/bin/packer-post-processor-vagrant
2015/12/04 18:00:36 [DEBUG] Discovered plugin: vagrant-cloud = /usr/local/bin/packer-post-processor-vagrant-cloud
2015/12/04 18:00:36 [DEBUG] Discovered plugin: vsphere = /usr/local/bin/packer-post-processor-vsphere
2015/12/04 18:00:36 [DEBUG] Discovered plugin: ansible-local = /usr/local/bin/packer-provisioner-ansible-local
2015/12/04 18:00:36 [DEBUG] Discovered plugin: chef-client = /usr/local/bin/packer-provisioner-chef-client
2015/12/04 18:00:36 [DEBUG] Discovered plugin: chef-solo = /usr/local/bin/packer-provisioner-chef-solo
2015/12/04 18:00:36 [DEBUG] Discovered plugin: file = /usr/local/bin/packer-provisioner-file
2015/12/04 18:00:36 [DEBUG] Discovered plugin: powershell = /usr/local/bin/packer-provisioner-powershell
2015/12/04 18:00:36 [DEBUG] Discovered plugin: puppet-masterless = /usr/local/bin/packer-provisioner-puppet-masterless
2015/12/04 18:00:36 [DEBUG] Discovered plugin: puppet-server = /usr/local/bin/packer-provisioner-puppet-server
2015/12/04 18:00:36 [DEBUG] Discovered plugin: salt-masterless = /usr/local/bin/packer-provisioner-salt-masterless
2015/12/04 18:00:36 [DEBUG] Discovered plugin: shell = /usr/local/bin/packer-provisioner-shell
2015/12/04 18:00:36 [DEBUG] Discovered plugin: shell-local = /usr/local/bin/packer-provisioner-shell-local
2015/12/04 18:00:36 [DEBUG] Discovered plugin: windows-restart = /usr/local/bin/packer-provisioner-windows-restart
2015/12/04 18:00:36 [DEBUG] Discovered plugin: windows-shell = /usr/local/bin/packer-provisioner-windows-shell
2015/12/04 18:00:36 Detected home directory from env var: /Users/cbroglie
2015/12/04 18:00:36 Detected home directory from env var: /Users/cbroglie
2015/12/04 18:00:36 Attempting to open config file: /Users/cbroglie/.packerconfig
2015/12/04 18:00:36 [WARN] Config file doesn't exist: /Users/cbroglie/.packerconfig
2015/12/04 18:00:36 Packer config: &{DisableCheckpoint:false DisableCheckpointSignature:false PluginMinPort:10000 PluginMaxPort:25000 Builders:map[amazon-instance:/usr/local/bin/packer-builder-amazon-instance digitalocean:/usr/local/bin/packer-builder-digitalocean null:/usr/local/bin/packer-builder-null vmware-iso:/usr/local/bin/packer-builder-vmware-iso vmware-vmx:/usr/local/bin/packer-builder-vmware-vmx amazon-ebs:/usr/local/bin/packer-builder-amazon-ebs file:/usr/local/bin/packer-builder-file openstack:/usr/local/bin/packer-builder-openstack virtualbox-ovf:/usr/local/bin/packer-builder-virtualbox-ovf amazon-chroot:/usr/local/bin/packer-builder-amazon-chroot docker:/usr/local/bin/packer-builder-docker googlecompute:/usr/local/bin/packer-builder-googlecompute virtualbox-iso:/usr/local/bin/packer-builder-virtualbox-iso parallels-iso:/usr/local/bin/packer-builder-parallels-iso parallels-pvm:/usr/local/bin/packer-builder-parallels-pvm qemu:/usr/local/bin/packer-builder-qemu] PostProcessors:map[docker-save:/usr/local/bin/packer-post-processor-docker-save docker-tag:/usr/local/bin/packer-post-processor-docker-tag vagrant-cloud:/usr/local/bin/packer-post-processor-vagrant-cloud atlas:/usr/local/bin/packer-post-processor-atlas compress:/usr/local/bin/packer-post-processor-compress docker-import:/usr/local/bin/packer-post-processor-docker-import vsphere:/usr/local/bin/packer-post-processor-vsphere artifice:/usr/local/bin/packer-post-processor-artifice docker-push:/usr/local/bin/packer-post-processor-docker-push vagrant:/usr/local/bin/packer-post-processor-vagrant] Provisioners:map[ansible-local:/usr/local/bin/packer-provisioner-ansible-local chef-client:/usr/local/bin/packer-provisioner-chef-client chef-solo:/usr/local/bin/packer-provisioner-chef-solo file:/usr/local/bin/packer-provisioner-file powershell:/usr/local/bin/packer-provisioner-powershell salt-masterless:/usr/local/bin/packer-provisioner-salt-masterless windows-restart:/usr/local/bin/packer-provisioner-windows-restart puppet-masterless:/usr/local/bin/packer-provisioner-puppet-masterless puppet-server:/usr/local/bin/packer-provisioner-puppet-server shell:/usr/local/bin/packer-provisioner-shell shell-local:/usr/local/bin/packer-provisioner-shell-local windows-shell:/usr/local/bin/packer-provisioner-windows-shell]}
2015/12/04 18:00:36 Setting cache directory: /Users/cbroglie/Workspace/dapiPlugin-sample/packer/packer_cache
2015/12/04 18:00:36 Detected home directory from env var: /Users/cbroglie
2015/12/04 18:00:36 Loading builder: docker
2015/12/04 18:00:36 Creating plugin client for path: /usr/local/bin/packer-builder-docker
2015/12/04 18:00:36 Starting plugin: /usr/local/bin/packer-builder-docker []string{"/usr/local/bin/packer-builder-docker"}
2015/12/04 18:00:36 Waiting for RPC address for: /usr/local/bin/packer-builder-docker
2015/12/04 18:00:36 packer-builder-docker: 2015/12/04 18:00:36 Plugin minimum port: 10000
2015/12/04 18:00:36 packer-builder-docker: 2015/12/04 18:00:36 Plugin maximum port: 25000
2015/12/04 18:00:36 packer-builder-docker: 2015/12/04 18:00:36 Plugin address: unix /var/folders/53/117c27k55hvgvcn0vt19kh2w0000gp/T/packer-plugin599393303
2015/12/04 18:00:36 packer-builder-docker: 2015/12/04 18:00:36 Waiting for connection...
2015/12/04 18:00:36 packer-builder-docker: 2015/12/04 18:00:36 Serving a plugin connection...
2015/12/04 18:00:36 Loading provisioner: chef-solo
2015/12/04 18:00:36 Creating plugin client for path: /usr/local/bin/packer-provisioner-chef-solo
2015/12/04 18:00:36 Starting plugin: /usr/local/bin/packer-provisioner-chef-solo []string{"/usr/local/bin/packer-provisioner-chef-solo"}
2015/12/04 18:00:36 Waiting for RPC address for: /usr/local/bin/packer-provisioner-chef-solo
2015/12/04 18:00:36 packer-provisioner-chef-solo: 2015/12/04 18:00:36 Plugin minimum port: 10000
2015/12/04 18:00:36 packer-provisioner-chef-solo: 2015/12/04 18:00:36 Plugin maximum port: 25000
2015/12/04 18:00:36 packer-provisioner-chef-solo: 2015/12/04 18:00:36 Plugin address: unix /var/folders/53/117c27k55hvgvcn0vt19kh2w0000gp/T/packer-plugin030120354
2015/12/04 18:00:36 packer-provisioner-chef-solo: 2015/12/04 18:00:36 Waiting for connection...
2015/12/04 18:00:36 packer-provisioner-chef-solo: 2015/12/04 18:00:36 Serving a plugin connection...
2015/12/04 18:00:36 Loading post-processor: docker-tag
2015/12/04 18:00:36 Creating plugin client for path: /usr/local/bin/packer-post-processor-docker-tag
2015/12/04 18:00:36 Starting plugin: /usr/local/bin/packer-post-processor-docker-tag []string{"/usr/local/bin/packer-post-processor-docker-tag"}
2015/12/04 18:00:36 Waiting for RPC address for: /usr/local/bin/packer-post-processor-docker-tag
2015/12/04 18:00:36 packer-post-processor-docker-tag: 2015/12/04 18:00:36 Plugin minimum port: 10000
2015/12/04 18:00:36 packer-post-processor-docker-tag: 2015/12/04 18:00:36 Plugin maximum port: 25000
2015/12/04 18:00:36 packer-post-processor-docker-tag: 2015/12/04 18:00:36 Plugin address: unix /var/folders/53/117c27k55hvgvcn0vt19kh2w0000gp/T/packer-plugin125988427
2015/12/04 18:00:36 packer-post-processor-docker-tag: 2015/12/04 18:00:36 Waiting for connection...
2015/12/04 18:00:36 packer-post-processor-docker-tag: 2015/12/04 18:00:36 Serving a plugin connection...
2015/12/04 18:00:36 ui: docker output will be in this color.
2015/12/04 18:00:36 ui:
2015/12/04 18:00:36 Build debug mode: false
2015/12/04 18:00:36 Force build: false
2015/12/04 18:00:36 Preparing build: docker
docker output will be in this color.

2015/12/04 18:00:36 Waiting on builds to complete...
2015/12/04 18:00:36 Starting build run: docker
2015/12/04 18:00:36 Running builder: docker
2015/12/04 18:00:36 packer-builder-docker: 2015/12/04 18:00:36 [DEBUG] Docker version: 1.9.1
2015/12/04 18:00:36 packer-builder-docker: 2015/12/04 18:00:36 [DEBUG] Container will be committed
2015/12/04 18:00:36 ui: ==> docker: Creating a temporary directory for sharing data...
==> docker: Creating a temporary directory for sharing data...
2015/12/04 18:00:36 ui: ==> docker: Pulling Docker image: centos:5.11
==> docker: Pulling Docker image: centos:5.11
2015/12/04 18:00:36 packer-builder-docker: 2015/12/04 18:00:36 Executing: /usr/local/bin/docker [pull centos:5.11]
2015/12/04 18:00:38 ui:     docker: 5.11: Pulling from library/centos
    docker: 5.11: Pulling from library/centos
2015/12/04 18:00:38 ui:     docker: Digest: sha256:7f8a808416f712da6931ac65e4308fede7fe86bcf15364b6f63af88840fe6131
    docker: Digest: sha256:7f8a808416f712da6931ac65e4308fede7fe86bcf15364b6f63af88840fe6131
2015/12/04 18:00:38 ui:     docker: Status: Image is up to date for centos:5.11
    docker: Status: Image is up to date for centos:5.11
2015/12/04 18:00:38 ui: ==> docker: Starting docker container...
==> docker: Starting docker container...
2015/12/04 18:00:38 ui:     docker: Run command: docker run -v /var/folders/53/117c27k55hvgvcn0vt19kh2w0000gp/T/packer-docker428588682:/packer-files -d -i -t centos:5.11 /bin/bash
    docker: Run command: docker run -v /var/folders/53/117c27k55hvgvcn0vt19kh2w0000gp/T/packer-docker428588682:/packer-files -d -i -t centos:5.11 /bin/bash
2015/12/04 18:00:38 packer-builder-docker: 2015/12/04 18:00:38 Starting container with args: [run -v /var/folders/53/117c27k55hvgvcn0vt19kh2w0000gp/T/packer-docker428588682:/packer-files -d -i -t centos:5.11 /bin/bash]
2015/12/04 18:00:38 packer-builder-docker: 2015/12/04 18:00:38 Waiting for container to finish starting
2015/12/04 18:00:38 ui:     docker: Container ID: da22351519c32c23be79e48334b0d23308ee9f783a6c026b55330bea5177bb4d
    docker: Container ID: da22351519c32c23be79e48334b0d23308ee9f783a6c026b55330bea5177bb4d
2015/12/04 18:00:38 packer-builder-docker: 2015/12/04 18:00:38 Running the provision hook
2015/12/04 18:00:38 ui: ==> docker: Provisioning with chef-solo
==> docker: Provisioning with chef-solo
2015/12/04 18:00:38 ui:     docker: Installing Chef...
    docker: Installing Chef...
2015/12/04 18:00:38 packer-builder-docker: 2015/12/04 18:00:38 Executing in container da22351519c32c23be79e48334b0d23308ee9f783a6c026b55330bea5177bb4d: "(curl -L https://www.opscode.com/chef/install.sh | sudo bash) >/packer-files/cmd895978593 2>&1; echo $? >/packer-files/cmd895978593-exit"
2015/12/04 18:00:40 packer-builder-docker: 2015/12/04 18:00:40 Waiting for exit code to appear for remote command...
```

Using packer v0.8.6:
```
$ packer version
Packer v0.8.6

$
```

I attached to the container and can saw that the command has run (and failed):
```
[root@da22351519c3 /]# ls /packer-files/
cmd895978593  cmd895978593-exit
[root@da22351519c3 /]# cat /packer-files/cmd895978593
/bin/sh: line 1: sudo: command not found
/bin/sh: line 1: curl: command not found
[root@da22351519c3 /]#
```

Installing sudo and curl gets me moving, but I'm reporting the bug b/c packer is hanging rather than seeing that the command to install chef-solo has failed. Thanks.

**Comment by cbroglie** [comment]
Spoke too soon about getting past it, adding an inline shell provisioner ahead of chef-solo also fails and hangs. Here is the output from the container:
```
[root@9c72568275fd /]# ls /packer-files/
cmd640244936  cmd640244936-exit
[root@9c72568275fd /]# cat /packer-files/cmd640244936
cp: cannot stat `/packer-files/upload773629901': No such file or directory
[root@9c72568275fd /]#
```

And here is the packer output up to where it hangs:
```
$ PACKER_LOG=1 packer build docker.json
2015/12/04 18:21:45 [INFO] Packer version: 0.8.6  f8f7b7a34c1be06058f5aca23a51247db12cdbc5+CHANGES
2015/12/04 18:21:45 Packer Target OS/Arch: darwin amd64
2015/12/04 18:21:45 Built with Go Version: go1.5
2015/12/04 18:21:45 [DEBUG] Discovered plugin: amazon-chroot = /usr/local/bin/packer-builder-amazon-chroot
2015/12/04 18:21:45 [DEBUG] Discovered plugin: amazon-ebs = /usr/local/bin/packer-builder-amazon-ebs
2015/12/04 18:21:45 [DEBUG] Discovered plugin: amazon-instance = /usr/local/bin/packer-builder-amazon-instance
2015/12/04 18:21:45 [DEBUG] Discovered plugin: digitalocean = /usr/local/bin/packer-builder-digitalocean
2015/12/04 18:21:45 [DEBUG] Discovered plugin: docker = /usr/local/bin/packer-builder-docker
2015/12/04 18:21:45 [DEBUG] Discovered plugin: file = /usr/local/bin/packer-builder-file
2015/12/04 18:21:45 [DEBUG] Discovered plugin: googlecompute = /usr/local/bin/packer-builder-googlecompute
2015/12/04 18:21:45 [DEBUG] Discovered plugin: null = /usr/local/bin/packer-builder-null
2015/12/04 18:21:45 [DEBUG] Discovered plugin: openstack = /usr/local/bin/packer-builder-openstack
2015/12/04 18:21:45 [DEBUG] Discovered plugin: parallels-iso = /usr/local/bin/packer-builder-parallels-iso
2015/12/04 18:21:45 [DEBUG] Discovered plugin: parallels-pvm = /usr/local/bin/packer-builder-parallels-pvm
2015/12/04 18:21:45 [DEBUG] Discovered plugin: qemu = /usr/local/bin/packer-builder-qemu
2015/12/04 18:21:45 [DEBUG] Discovered plugin: virtualbox-iso = /usr/local/bin/packer-builder-virtualbox-iso
2015/12/04 18:21:45 [DEBUG] Discovered plugin: virtualbox-ovf = /usr/local/bin/packer-builder-virtualbox-ovf
2015/12/04 18:21:45 [DEBUG] Discovered plugin: vmware-iso = /usr/local/bin/packer-builder-vmware-iso
2015/12/04 18:21:45 [DEBUG] Discovered plugin: vmware-vmx = /usr/local/bin/packer-builder-vmware-vmx
2015/12/04 18:21:45 [DEBUG] Discovered plugin: artifice = /usr/local/bin/packer-post-processor-artifice
2015/12/04 18:21:45 [DEBUG] Discovered plugin: atlas = /usr/local/bin/packer-post-processor-atlas
2015/12/04 18:21:45 [DEBUG] Discovered plugin: compress = /usr/local/bin/packer-post-processor-compress
2015/12/04 18:21:45 [DEBUG] Discovered plugin: docker-import = /usr/local/bin/packer-post-processor-docker-import
2015/12/04 18:21:45 [DEBUG] Discovered plugin: docker-push = /usr/local/bin/packer-post-processor-docker-push
2015/12/04 18:21:45 [DEBUG] Discovered plugin: docker-save = /usr/local/bin/packer-post-processor-docker-save
2015/12/04 18:21:45 [DEBUG] Discovered plugin: docker-tag = /usr/local/bin/packer-post-processor-docker-tag
2015/12/04 18:21:45 [DEBUG] Discovered plugin: vagrant = /usr/local/bin/packer-post-processor-vagrant
2015/12/04 18:21:45 [DEBUG] Discovered plugin: vagrant-cloud = /usr/local/bin/packer-post-processor-vagrant-cloud
2015/12/04 18:21:45 [DEBUG] Discovered plugin: vsphere = /usr/local/bin/packer-post-processor-vsphere
2015/12/04 18:21:45 [DEBUG] Discovered plugin: ansible-local = /usr/local/bin/packer-provisioner-ansible-local
2015/12/04 18:21:45 [DEBUG] Discovered plugin: chef-client = /usr/local/bin/packer-provisioner-chef-client
2015/12/04 18:21:45 [DEBUG] Discovered plugin: chef-solo = /usr/local/bin/packer-provisioner-chef-solo
2015/12/04 18:21:45 [DEBUG] Discovered plugin: file = /usr/local/bin/packer-provisioner-file
2015/12/04 18:21:45 [DEBUG] Discovered plugin: powershell = /usr/local/bin/packer-provisioner-powershell
2015/12/04 18:21:45 [DEBUG] Discovered plugin: puppet-masterless = /usr/local/bin/packer-provisioner-puppet-masterless
2015/12/04 18:21:45 [DEBUG] Discovered plugin: puppet-server = /usr/local/bin/packer-provisioner-puppet-server
2015/12/04 18:21:45 [DEBUG] Discovered plugin: salt-masterless = /usr/local/bin/packer-provisioner-salt-masterless
2015/12/04 18:21:45 [DEBUG] Discovered plugin: shell = /usr/local/bin/packer-provisioner-shell
2015/12/04 18:21:45 [DEBUG] Discovered plugin: shell-local = /usr/local/bin/packer-provisioner-shell-local
2015/12/04 18:21:45 [DEBUG] Discovered plugin: windows-restart = /usr/local/bin/packer-provisioner-windows-restart
2015/12/04 18:21:45 [DEBUG] Discovered plugin: windows-shell = /usr/local/bin/packer-provisioner-windows-shell
2015/12/04 18:21:45 Detected home directory from env var: /Users/cbroglie
2015/12/04 18:21:45 Detected home directory from env var: /Users/cbroglie
2015/12/04 18:21:45 Attempting to open config file: /Users/cbroglie/.packerconfig
2015/12/04 18:21:45 [WARN] Config file doesn't exist: /Users/cbroglie/.packerconfig
2015/12/04 18:21:45 Packer config: &{DisableCheckpoint:false DisableCheckpointSignature:false PluginMinPort:10000 PluginMaxPort:25000 Builders:map[amazon-ebs:/usr/local/bin/packer-builder-amazon-ebs virtualbox-iso:/usr/local/bin/packer-builder-virtualbox-iso virtualbox-ovf:/usr/local/bin/packer-builder-virtualbox-ovf vmware-iso:/usr/local/bin/packer-builder-vmware-iso amazon-chroot:/usr/local/bin/packer-builder-amazon-chroot amazon-instance:/usr/local/bin/packer-builder-amazon-instance digitalocean:/usr/local/bin/packer-builder-digitalocean docker:/usr/local/bin/packer-builder-docker qemu:/usr/local/bin/packer-builder-qemu vmware-vmx:/usr/local/bin/packer-builder-vmware-vmx null:/usr/local/bin/packer-builder-null parallels-iso:/usr/local/bin/packer-builder-parallels-iso file:/usr/local/bin/packer-builder-file googlecompute:/usr/local/bin/packer-builder-googlecompute openstack:/usr/local/bin/packer-builder-openstack parallels-pvm:/usr/local/bin/packer-builder-parallels-pvm] PostProcessors:map[docker-import:/usr/local/bin/packer-post-processor-docker-import docker-push:/usr/local/bin/packer-post-processor-docker-push docker-save:/usr/local/bin/packer-post-processor-docker-save docker-tag:/usr/local/bin/packer-post-processor-docker-tag vagrant:/usr/local/bin/packer-post-processor-vagrant vagrant-cloud:/usr/local/bin/packer-post-processor-vagrant-cloud artifice:/usr/local/bin/packer-post-processor-artifice atlas:/usr/local/bin/packer-post-processor-atlas compress:/usr/local/bin/packer-post-processor-compress vsphere:/usr/local/bin/packer-post-processor-vsphere] Provisioners:map[ansible-local:/usr/local/bin/packer-provisioner-ansible-local chef-client:/usr/local/bin/packer-provisioner-chef-client puppet-server:/usr/local/bin/packer-provisioner-puppet-server salt-masterless:/usr/local/bin/packer-provisioner-salt-masterless windows-shell:/usr/local/bin/packer-provisioner-windows-shell shell-local:/usr/local/bin/packer-provisioner-shell-local windows-restart:/usr/local/bin/packer-provisioner-windows-restart chef-solo:/usr/local/bin/packer-provisioner-chef-solo file:/usr/local/bin/packer-provisioner-file powershell:/usr/local/bin/packer-provisioner-powershell puppet-masterless:/usr/local/bin/packer-provisioner-puppet-masterless shell:/usr/local/bin/packer-provisioner-shell]}
2015/12/04 18:21:45 Setting cache directory: /Users/cbroglie/Workspace/dapiPlugin-sample/packer/packer_cache
2015/12/04 18:21:45 Detected home directory from env var: /Users/cbroglie
2015/12/04 18:21:45 Loading builder: docker
2015/12/04 18:21:45 Creating plugin client for path: /usr/local/bin/packer-builder-docker
2015/12/04 18:21:45 Starting plugin: /usr/local/bin/packer-builder-docker []string{"/usr/local/bin/packer-builder-docker"}
2015/12/04 18:21:45 Waiting for RPC address for: /usr/local/bin/packer-builder-docker
2015/12/04 18:21:45 packer-builder-docker: 2015/12/04 18:21:45 Plugin minimum port: 10000
2015/12/04 18:21:45 packer-builder-docker: 2015/12/04 18:21:45 Plugin maximum port: 25000
2015/12/04 18:21:45 packer-builder-docker: 2015/12/04 18:21:45 Plugin address: unix /var/folders/53/117c27k55hvgvcn0vt19kh2w0000gp/T/packer-plugin137726371
2015/12/04 18:21:45 packer-builder-docker: 2015/12/04 18:21:45 Waiting for connection...
2015/12/04 18:21:45 packer-builder-docker: 2015/12/04 18:21:45 Serving a plugin connection...
2015/12/04 18:21:45 Loading provisioner: shell
2015/12/04 18:21:45 Creating plugin client for path: /usr/local/bin/packer-provisioner-shell
2015/12/04 18:21:45 Starting plugin: /usr/local/bin/packer-provisioner-shell []string{"/usr/local/bin/packer-provisioner-shell"}
2015/12/04 18:21:45 Waiting for RPC address for: /usr/local/bin/packer-provisioner-shell
2015/12/04 18:21:45 packer-provisioner-shell: 2015/12/04 18:21:45 Plugin minimum port: 10000
2015/12/04 18:21:45 packer-provisioner-shell: 2015/12/04 18:21:45 Plugin maximum port: 25000
2015/12/04 18:21:45 packer-provisioner-shell: 2015/12/04 18:21:45 Plugin address: unix /var/folders/53/117c27k55hvgvcn0vt19kh2w0000gp/T/packer-plugin470121940
2015/12/04 18:21:45 packer-provisioner-shell: 2015/12/04 18:21:45 Waiting for connection...
2015/12/04 18:21:45 packer-provisioner-shell: 2015/12/04 18:21:45 Serving a plugin connection...
2015/12/04 18:21:45 Loading provisioner: chef-solo
2015/12/04 18:21:45 Creating plugin client for path: /usr/local/bin/packer-provisioner-chef-solo
2015/12/04 18:21:45 Starting plugin: /usr/local/bin/packer-provisioner-chef-solo []string{"/usr/local/bin/packer-provisioner-chef-solo"}
2015/12/04 18:21:45 Waiting for RPC address for: /usr/local/bin/packer-provisioner-chef-solo
2015/12/04 18:21:45 packer-provisioner-chef-solo: 2015/12/04 18:21:45 Plugin minimum port: 10000
2015/12/04 18:21:45 packer-provisioner-chef-solo: 2015/12/04 18:21:45 Plugin maximum port: 25000
2015/12/04 18:21:45 packer-provisioner-chef-solo: 2015/12/04 18:21:45 Plugin address: unix /var/folders/53/117c27k55hvgvcn0vt19kh2w0000gp/T/packer-plugin717816182
2015/12/04 18:21:45 packer-provisioner-chef-solo: 2015/12/04 18:21:45 Waiting for connection...
2015/12/04 18:21:45 packer-provisioner-chef-solo: 2015/12/04 18:21:45 Serving a plugin connection...
2015/12/04 18:21:45 Loading post-processor: docker-tag
2015/12/04 18:21:45 Creating plugin client for path: /usr/local/bin/packer-post-processor-docker-tag
2015/12/04 18:21:45 Starting plugin: /usr/local/bin/packer-post-processor-docker-tag []string{"/usr/local/bin/packer-post-processor-docker-tag"}
2015/12/04 18:21:45 Waiting for RPC address for: /usr/local/bin/packer-post-processor-docker-tag
2015/12/04 18:21:45 packer-post-processor-docker-tag: 2015/12/04 18:21:45 Plugin minimum port: 10000
2015/12/04 18:21:45 packer-post-processor-docker-tag: 2015/12/04 18:21:45 Plugin maximum port: 25000
2015/12/04 18:21:45 packer-post-processor-docker-tag: 2015/12/04 18:21:45 Plugin address: unix /var/folders/53/117c27k55hvgvcn0vt19kh2w0000gp/T/packer-plugin874081606
2015/12/04 18:21:45 packer-post-processor-docker-tag: 2015/12/04 18:21:45 Waiting for connection...
2015/12/04 18:21:45 packer-post-processor-docker-tag: 2015/12/04 18:21:45 Serving a plugin connection...
2015/12/04 18:21:45 ui: docker output will be in this color.
2015/12/04 18:21:45 ui:
2015/12/04 18:21:45 Build debug mode: false
2015/12/04 18:21:45 Force build: false
2015/12/04 18:21:45 Preparing build: docker
docker output will be in this color.

2015/12/04 18:21:45 Waiting on builds to complete...
2015/12/04 18:21:45 Starting build run: docker
2015/12/04 18:21:45 Running builder: docker
2015/12/04 18:21:45 packer-builder-docker: 2015/12/04 18:21:45 [DEBUG] Docker version: 1.9.1
2015/12/04 18:21:45 packer-builder-docker: 2015/12/04 18:21:45 [DEBUG] Container will be committed
2015/12/04 18:21:45 ui: ==> docker: Creating a temporary directory for sharing data...
==> docker: Creating a temporary directory for sharing data...
2015/12/04 18:21:45 ui: ==> docker: Pulling Docker image: centos:5.11
==> docker: Pulling Docker image: centos:5.11
2015/12/04 18:21:45 packer-builder-docker: 2015/12/04 18:21:45 Executing: /usr/local/bin/docker [pull centos:5.11]
2015/12/04 18:21:48 ui:     docker: 5.11: Pulling from library/centos
    docker: 5.11: Pulling from library/centos
2015/12/04 18:21:48 ui:     docker: Digest: sha256:7f8a808416f712da6931ac65e4308fede7fe86bcf15364b6f63af88840fe6131
    docker: Digest: sha256:7f8a808416f712da6931ac65e4308fede7fe86bcf15364b6f63af88840fe6131
2015/12/04 18:21:48 ui:     docker: Status: Image is up to date for centos:5.11
    docker: Status: Image is up to date for centos:5.11
2015/12/04 18:21:48 ui: ==> docker: Starting docker container...
==> docker: Starting docker container...
2015/12/04 18:21:48 ui:     docker: Run command: docker run -v /var/folders/53/117c27k55hvgvcn0vt19kh2w0000gp/T/packer-docker035736230:/packer-files -d -i -t centos:5.11 /bin/bash
    docker: Run command: docker run -v /var/folders/53/117c27k55hvgvcn0vt19kh2w0000gp/T/packer-docker035736230:/packer-files -d -i -t centos:5.11 /bin/bash
2015/12/04 18:21:48 packer-builder-docker: 2015/12/04 18:21:48 Starting container with args: [run -v /var/folders/53/117c27k55hvgvcn0vt19kh2w0000gp/T/packer-docker035736230:/packer-files -d -i -t centos:5.11 /bin/bash]
2015/12/04 18:21:48 packer-builder-docker: 2015/12/04 18:21:48 Waiting for container to finish starting
2015/12/04 18:21:48 ui:     docker: Container ID: 9c72568275fd1b5adb2038c2c551d919969df29187fdf253f7dc48cb14c31928
    docker: Container ID: 9c72568275fd1b5adb2038c2c551d919969df29187fdf253f7dc48cb14c31928
2015/12/04 18:21:48 packer-builder-docker: 2015/12/04 18:21:48 Running the provision hook
2015/12/04 18:21:48 ui: ==> docker: Provisioning with shell script: /var/folders/53/117c27k55hvgvcn0vt19kh2w0000gp/T/packer-shell788187939
==> docker: Provisioning with shell script: /var/folders/53/117c27k55hvgvcn0vt19kh2w0000gp/T/packer-shell788187939
2015/12/04 18:21:48 packer-provisioner-shell: 2015/12/04 18:21:48 Opening /var/folders/53/117c27k55hvgvcn0vt19kh2w0000gp/T/packer-shell788187939 for reading
2015/12/04 18:21:48 packer-provisioner-shell: 2015/12/04 18:21:48 [INFO] 51 bytes written for 'uploadData'
2015/12/04 18:21:48 [INFO] 51 bytes written for 'uploadData'
2015/12/04 18:21:48 packer-builder-docker: 2015/12/04 18:21:48 Executing in container 9c72568275fd1b5adb2038c2c551d919969df29187fdf253f7dc48cb14c31928: "(command cp /packer-files/upload773629901 /tmp/script_7943.sh) >/packer-files/cmd640244936 2>&1; echo $? >/packer-files/cmd640244936-exit"
2015/12/04 18:21:50 packer-builder-docker: 2015/12/04 18:21:50 Waiting for exit code to appear for remote command...
```

**Comment by cbroglie** [comment]
Ok, turns out this issue only occurs when I run on Mac OS - it works fine when running on Linux.

**Comment by markpeek** [comment]
This has been fixed on master (bc0f438db0b77717994420076f8505d780dc3ca0). The current folder was not being mapped into the vm on the Mac which caused the failure.

**Comment by cbroglie** [comment]
Thanks @markpeek, but I'm still experiencing this after building from master:

```
$ PACKER_LOG=1 packer build docker.json
2015/12/07 16:02:57 [INFO] Packer version: 0.8.7 dev 692b227ac3c9e6879e14e19e11b6cd6df4f1c4d9
2015/12/07 16:02:57 Packer Target OS/Arch: darwin amd64
2015/12/07 16:02:57 Built with Go Version: go1.5.1
2015/12/07 16:02:57 [DEBUG] Discovered plugin: amazon-chroot = /usr/local/Cellar/packer/0.8.6/bin/packer-builder-amazon-chroot
2015/12/07 16:02:57 [DEBUG] Discovered plugin: amazon-ebs = /usr/local/Cellar/packer/0.8.6/bin/packer-builder-amazon-ebs
2015/12/07 16:02:57 [DEBUG] Discovered plugin: amazon-instance = /usr/local/Cellar/packer/0.8.6/bin/packer-builder-amazon-instance
2015/12/07 16:02:57 [DEBUG] Discovered plugin: digitalocean = /usr/local/Cellar/packer/0.8.6/bin/packer-builder-digitalocean
2015/12/07 16:02:57 [DEBUG] Discovered plugin: docker = /usr/local/Cellar/packer/0.8.6/bin/packer-builder-docker
2015/12/07 16:02:57 [DEBUG] Discovered plugin: file = /usr/local/Cellar/packer/0.8.6/bin/packer-builder-file
2015/12/07 16:02:57 [DEBUG] Discovered plugin: googlecompute = /usr/local/Cellar/packer/0.8.6/bin/packer-builder-googlecompute
2015/12/07 16:02:57 [DEBUG] Discovered plugin: null = /usr/local/Cellar/packer/0.8.6/bin/packer-builder-null
2015/12/07 16:02:57 [DEBUG] Discovered plugin: openstack = /usr/local/Cellar/packer/0.8.6/bin/packer-builder-openstack
2015/12/07 16:02:57 [DEBUG] Discovered plugin: parallels-iso = /usr/local/Cellar/packer/0.8.6/bin/packer-builder-parallels-iso
2015/12/07 16:02:57 [DEBUG] Discovered plugin: parallels-pvm = /usr/local/Cellar/packer/0.8.6/bin/packer-builder-parallels-pvm
2015/12/07 16:02:57 [DEBUG] Discovered plugin: qemu = /usr/local/Cellar/packer/0.8.6/bin/packer-builder-qemu
2015/12/07 16:02:57 [DEBUG] Discovered plugin: virtualbox-iso = /usr/local/Cellar/packer/0.8.6/bin/packer-builder-virtualbox-iso
2015/12/07 16:02:57 [DEBUG] Discovered plugin: virtualbox-ovf = /usr/local/Cellar/packer/0.8.6/bin/packer-builder-virtualbox-ovf
2015/12/07 16:02:57 [DEBUG] Discovered plugin: vmware-iso = /usr/local/Cellar/packer/0.8.6/bin/packer-builder-vmware-iso
2015/12/07 16:02:57 [DEBUG] Discovered plugin: vmware-vmx = /usr/local/Cellar/packer/0.8.6/bin/packer-builder-vmware-vmx
2015/12/07 16:02:57 [DEBUG] Discovered plugin: artifice = /usr/local/Cellar/packer/0.8.6/bin/packer-post-processor-artifice
2015/12/07 16:02:57 [DEBUG] Discovered plugin: atlas = /usr/local/Cellar/packer/0.8.6/bin/packer-post-processor-atlas
2015/12/07 16:02:57 [DEBUG] Discovered plugin: compress = /usr/local/Cellar/packer/0.8.6/bin/packer-post-processor-compress
2015/12/07 16:02:57 [DEBUG] Discovered plugin: docker-import = /usr/local/Cellar/packer/0.8.6/bin/packer-post-processor-docker-import
2015/12/07 16:02:57 [DEBUG] Discovered plugin: docker-push = /usr/local/Cellar/packer/0.8.6/bin/packer-post-processor-docker-push
2015/12/07 16:02:57 [DEBUG] Discovered plugin: docker-save = /usr/local/Cellar/packer/0.8.6/bin/packer-post-processor-docker-save
2015/12/07 16:02:57 [DEBUG] Discovered plugin: docker-tag = /usr/local/Cellar/packer/0.8.6/bin/packer-post-processor-docker-tag
2015/12/07 16:02:57 [DEBUG] Discovered plugin: vagrant = /usr/local/Cellar/packer/0.8.6/bin/packer-post-processor-vagrant
2015/12/07 16:02:57 [DEBUG] Discovered plugin: vagrant-cloud = /usr/local/Cellar/packer/0.8.6/bin/packer-post-processor-vagrant-cloud
2015/12/07 16:02:57 [DEBUG] Discovered plugin: vsphere = /usr/local/Cellar/packer/0.8.6/bin/packer-post-processor-vsphere
2015/12/07 16:02:57 [DEBUG] Discovered plugin: ansible-local = /usr/local/Cellar/packer/0.8.6/bin/packer-provisioner-ansible-local
2015/12/07 16:02:57 [DEBUG] Discovered plugin: chef-client = /usr/local/Cellar/packer/0.8.6/bin/packer-provisioner-chef-client
2015/12/07 16:02:57 [DEBUG] Discovered plugin: chef-solo = /usr/local/Cellar/packer/0.8.6/bin/packer-provisioner-chef-solo
2015/12/07 16:02:57 [DEBUG] Discovered plugin: file = /usr/local/Cellar/packer/0.8.6/bin/packer-provisioner-file
2015/12/07 16:02:57 [DEBUG] Discovered plugin: powershell = /usr/local/Cellar/packer/0.8.6/bin/packer-provisioner-powershell
2015/12/07 16:02:57 [DEBUG] Discovered plugin: puppet-masterless = /usr/local/Cellar/packer/0.8.6/bin/packer-provisioner-puppet-masterless
2015/12/07 16:02:57 [DEBUG] Discovered plugin: puppet-server = /usr/local/Cellar/packer/0.8.6/bin/packer-provisioner-puppet-server
2015/12/07 16:02:57 [DEBUG] Discovered plugin: salt-masterless = /usr/local/Cellar/packer/0.8.6/bin/packer-provisioner-salt-masterless
2015/12/07 16:02:57 [DEBUG] Discovered plugin: shell = /usr/local/Cellar/packer/0.8.6/bin/packer-provisioner-shell
2015/12/07 16:02:57 [DEBUG] Discovered plugin: shell-local = /usr/local/Cellar/packer/0.8.6/bin/packer-provisioner-shell-local
2015/12/07 16:02:57 [DEBUG] Discovered plugin: windows-restart = /usr/local/Cellar/packer/0.8.6/bin/packer-provisioner-windows-restart
2015/12/07 16:02:57 [DEBUG] Discovered plugin: windows-shell = /usr/local/Cellar/packer/0.8.6/bin/packer-provisioner-windows-shell
2015/12/07 16:02:57 Detected home directory from env var: /Users/cbroglie
2015/12/07 16:02:57 Detected home directory from env var: /Users/cbroglie
2015/12/07 16:02:57 Attempting to open config file: /Users/cbroglie/.packerconfig
2015/12/07 16:02:57 [WARN] Config file doesn't exist: /Users/cbroglie/.packerconfig
2015/12/07 16:02:57 Packer config: &{DisableCheckpoint:false DisableCheckpointSignature:false PluginMinPort:10000 PluginMaxPort:25000 Builders:map[openstack:/usr/local/Cellar/packer/0.8.6/bin/packer-builder-openstack vmware-iso:/usr/local/Cellar/packer/0.8.6/bin/packer-builder-vmware-iso amazon-chroot:/usr/local/Cellar/packer/0.8.6/bin/packer-builder-amazon-chroot amazon-ebs:/usr/local/Cellar/packer/0.8.6/bin/packer-builder-amazon-ebs googlecompute:/usr/local/Cellar/packer/0.8.6/bin/packer-builder-googlecompute null:/usr/local/Cellar/packer/0.8.6/bin/packer-builder-null parallels-iso:/usr/local/Cellar/packer/0.8.6/bin/packer-builder-parallels-iso parallels-pvm:/usr/local/Cellar/packer/0.8.6/bin/packer-builder-parallels-pvm qemu:/usr/local/Cellar/packer/0.8.6/bin/packer-builder-qemu amazon-instance:/usr/local/Cellar/packer/0.8.6/bin/packer-builder-amazon-instance digitalocean:/usr/local/Cellar/packer/0.8.6/bin/packer-builder-digitalocean docker:/usr/local/Cellar/packer/0.8.6/bin/packer-builder-docker file:/usr/local/Cellar/packer/0.8.6/bin/packer-builder-file virtualbox-iso:/usr/local/Cellar/packer/0.8.6/bin/packer-builder-virtualbox-iso virtualbox-ovf:/usr/local/Cellar/packer/0.8.6/bin/packer-builder-virtualbox-ovf vmware-vmx:/usr/local/Cellar/packer/0.8.6/bin/packer-builder-vmware-vmx] PostProcessors:map[artifice:/usr/local/Cellar/packer/0.8.6/bin/packer-post-processor-artifice atlas:/usr/local/Cellar/packer/0.8.6/bin/packer-post-processor-atlas docker-import:/usr/local/Cellar/packer/0.8.6/bin/packer-post-processor-docker-import docker-push:/usr/local/Cellar/packer/0.8.6/bin/packer-post-processor-docker-push docker-tag:/usr/local/Cellar/packer/0.8.6/bin/packer-post-processor-docker-tag vagrant:/usr/local/Cellar/packer/0.8.6/bin/packer-post-processor-vagrant vagrant-cloud:/usr/local/Cellar/packer/0.8.6/bin/packer-post-processor-vagrant-cloud vsphere:/usr/local/Cellar/packer/0.8.6/bin/packer-post-processor-vsphere compress:/usr/local/Cellar/packer/0.8.6/bin/packer-post-processor-compress docker-save:/usr/local/Cellar/packer/0.8.6/bin/packer-post-processor-docker-save] Provisioners:map[shell:/usr/local/Cellar/packer/0.8.6/bin/packer-provisioner-shell windows-restart:/usr/local/Cellar/packer/0.8.6/bin/packer-provisioner-windows-restart ansible-local:/usr/local/Cellar/packer/0.8.6/bin/packer-provisioner-ansible-local chef-solo:/usr/local/Cellar/packer/0.8.6/bin/packer-provisioner-chef-solo powershell:/usr/local/Cellar/packer/0.8.6/bin/packer-provisioner-powershell puppet-masterless:/usr/local/Cellar/packer/0.8.6/bin/packer-provisioner-puppet-masterless puppet-server:/usr/local/Cellar/packer/0.8.6/bin/packer-provisioner-puppet-server salt-masterless:/usr/local/Cellar/packer/0.8.6/bin/packer-provisioner-salt-masterless chef-client:/usr/local/Cellar/packer/0.8.6/bin/packer-provisioner-chef-client file:/usr/local/Cellar/packer/0.8.6/bin/packer-provisioner-file shell-local:/usr/local/Cellar/packer/0.8.6/bin/packer-provisioner-shell-local windows-shell:/usr/local/Cellar/packer/0.8.6/bin/packer-provisioner-windows-shell]}
2015/12/07 16:02:57 Setting cache directory: /Users/cbroglie/Workspace/dapiPlugin-sample/packer/packer_cache
2015/12/07 16:02:57 Detected home directory from env var: /Users/cbroglie
2015/12/07 16:02:57 Loading builder: docker
2015/12/07 16:02:57 Creating plugin client for path: /usr/local/Cellar/packer/0.8.6/bin/packer-builder-docker
2015/12/07 16:02:57 Starting plugin: /usr/local/Cellar/packer/0.8.6/bin/packer-builder-docker []string{"/usr/local/Cellar/packer/0.8.6/bin/packer-builder-docker"}
2015/12/07 16:02:57 Waiting for RPC address for: /usr/local/Cellar/packer/0.8.6/bin/packer-builder-docker
2015/12/07 16:02:57 packer-builder-docker: 2015/12/07 16:02:57 Plugin minimum port: 10000
2015/12/07 16:02:57 packer-builder-docker: 2015/12/07 16:02:57 Plugin maximum port: 25000
2015/12/07 16:02:57 packer-builder-docker: 2015/12/07 16:02:57 Plugin address: unix /var/folders/53/117c27k55hvgvcn0vt19kh2w0000gp/T/packer-plugin511272476
2015/12/07 16:02:57 packer-builder-docker: 2015/12/07 16:02:57 Waiting for connection...
2015/12/07 16:02:57 packer-builder-docker: 2015/12/07 16:02:57 Serving a plugin connection...
2015/12/07 16:02:57 Loading provisioner: shell
2015/12/07 16:02:57 Creating plugin client for path: /usr/local/Cellar/packer/0.8.6/bin/packer-provisioner-shell
2015/12/07 16:02:57 Starting plugin: /usr/local/Cellar/packer/0.8.6/bin/packer-provisioner-shell []string{"/usr/local/Cellar/packer/0.8.6/bin/packer-provisioner-shell"}
2015/12/07 16:02:57 Waiting for RPC address for: /usr/local/Cellar/packer/0.8.6/bin/packer-provisioner-shell
2015/12/07 16:02:57 packer-provisioner-shell: 2015/12/07 16:02:57 Plugin minimum port: 10000
2015/12/07 16:02:57 packer-provisioner-shell: 2015/12/07 16:02:57 Plugin maximum port: 25000
2015/12/07 16:02:57 packer-provisioner-shell: 2015/12/07 16:02:57 Plugin address: unix /var/folders/53/117c27k55hvgvcn0vt19kh2w0000gp/T/packer-plugin385922986
2015/12/07 16:02:57 packer-provisioner-shell: 2015/12/07 16:02:57 Waiting for connection...
2015/12/07 16:02:57 packer-provisioner-shell: 2015/12/07 16:02:57 Serving a plugin connection...
2015/12/07 16:02:57 Loading provisioner: shell
2015/12/07 16:02:57 Creating plugin client for path: /usr/local/Cellar/packer/0.8.6/bin/packer-provisioner-shell
2015/12/07 16:02:57 Starting plugin: /usr/local/Cellar/packer/0.8.6/bin/packer-provisioner-shell []string{"/usr/local/Cellar/packer/0.8.6/bin/packer-provisioner-shell"}
2015/12/07 16:02:57 Waiting for RPC address for: /usr/local/Cellar/packer/0.8.6/bin/packer-provisioner-shell
2015/12/07 16:02:57 packer-provisioner-shell: 2015/12/07 16:02:57 Plugin minimum port: 10000
2015/12/07 16:02:57 packer-provisioner-shell: 2015/12/07 16:02:57 Plugin maximum port: 25000
2015/12/07 16:02:57 packer-provisioner-shell: 2015/12/07 16:02:57 Plugin address: unix /var/folders/53/117c27k55hvgvcn0vt19kh2w0000gp/T/packer-plugin151586566
2015/12/07 16:02:57 packer-provisioner-shell: 2015/12/07 16:02:57 Waiting for connection...
2015/12/07 16:02:57 packer-provisioner-shell: 2015/12/07 16:02:57 Serving a plugin connection...
2015/12/07 16:02:57 Loading provisioner: chef-solo
2015/12/07 16:02:57 Creating plugin client for path: /usr/local/Cellar/packer/0.8.6/bin/packer-provisioner-chef-solo
2015/12/07 16:02:57 Starting plugin: /usr/local/Cellar/packer/0.8.6/bin/packer-provisioner-chef-solo []string{"/usr/local/Cellar/packer/0.8.6/bin/packer-provisioner-chef-solo"}
2015/12/07 16:02:57 Waiting for RPC address for: /usr/local/Cellar/packer/0.8.6/bin/packer-provisioner-chef-solo
2015/12/07 16:02:57 packer-provisioner-chef-solo: 2015/12/07 16:02:57 Plugin minimum port: 10000
2015/12/07 16:02:57 packer-provisioner-chef-solo: 2015/12/07 16:02:57 Plugin maximum port: 25000
2015/12/07 16:02:57 packer-provisioner-chef-solo: 2015/12/07 16:02:57 Plugin address: unix /var/folders/53/117c27k55hvgvcn0vt19kh2w0000gp/T/packer-plugin674100690
2015/12/07 16:02:57 packer-provisioner-chef-solo: 2015/12/07 16:02:57 Waiting for connection...
2015/12/07 16:02:57 packer-provisioner-chef-solo: 2015/12/07 16:02:57 Serving a plugin connection...
2015/12/07 16:02:57 Loading post-processor: docker-tag
2015/12/07 16:02:57 Creating plugin client for path: /usr/local/Cellar/packer/0.8.6/bin/packer-post-processor-docker-tag
2015/12/07 16:02:57 Starting plugin: /usr/local/Cellar/packer/0.8.6/bin/packer-post-processor-docker-tag []string{"/usr/local/Cellar/packer/0.8.6/bin/packer-post-processor-docker-tag"}
2015/12/07 16:02:57 Waiting for RPC address for: /usr/local/Cellar/packer/0.8.6/bin/packer-post-processor-docker-tag
2015/12/07 16:02:57 packer-post-processor-docker-tag: 2015/12/07 16:02:57 Plugin minimum port: 10000
2015/12/07 16:02:57 packer-post-processor-docker-tag: 2015/12/07 16:02:57 Plugin maximum port: 25000
2015/12/07 16:02:57 packer-post-processor-docker-tag: 2015/12/07 16:02:57 Plugin address: unix /var/folders/53/117c27k55hvgvcn0vt19kh2w0000gp/T/packer-plugin415601998
2015/12/07 16:02:57 packer-post-processor-docker-tag: 2015/12/07 16:02:57 Waiting for connection...
2015/12/07 16:02:57 packer-post-processor-docker-tag: 2015/12/07 16:02:57 Serving a plugin connection...
2015/12/07 16:02:57 ui: docker output will be in this color.
2015/12/07 16:02:57 ui:
2015/12/07 16:02:57 Build debug mode: false
2015/12/07 16:02:57 Force build: false
2015/12/07 16:02:57 Preparing build: docker
docker output will be in this color.

2015/12/07 16:02:57 Waiting on builds to complete...
2015/12/07 16:02:57 Starting build run: docker
2015/12/07 16:02:57 Running builder: docker
2015/12/07 16:02:57 packer-builder-docker: 2015/12/07 16:02:57 [DEBUG] Docker version: 1.9.1
2015/12/07 16:02:57 packer-builder-docker: 2015/12/07 16:02:57 [DEBUG] Container will be committed
2015/12/07 16:02:57 ui: ==> docker: Creating a temporary directory for sharing data...
==> docker: Creating a temporary directory for sharing data...
2015/12/07 16:02:57 ui: ==> docker: Pulling Docker image: centos:5
==> docker: Pulling Docker image: centos:5
2015/12/07 16:02:57 packer-builder-docker: 2015/12/07 16:02:57 Executing: /usr/local/bin/docker [pull centos:5]
2015/12/07 16:02:59 ui:     docker: 5: Pulling from library/centos
    docker: 5: Pulling from library/centos
2015/12/07 16:02:59 ui:     docker: Digest: sha256:bd0bff820d491db21d981a9972ffa9e70d1f8b3447413c13d49acec8a928a63f
2015/12/07 16:02:59 ui:     docker: Status: Image is up to date for centos:5
    docker: Digest: sha256:bd0bff820d491db21d981a9972ffa9e70d1f8b3447413c13d49acec8a928a63f
    docker: Status: Image is up to date for centos:5
2015/12/07 16:02:59 ui: ==> docker: Starting docker container...
==> docker: Starting docker container...
2015/12/07 16:02:59 ui:     docker: Run command: docker run -v /var/folders/53/117c27k55hvgvcn0vt19kh2w0000gp/T/packer-docker206153419:/packer-files -d -i -t centos:5 /bin/bash
    docker: Run command: docker run -v /var/folders/53/117c27k55hvgvcn0vt19kh2w0000gp/T/packer-docker206153419:/packer-files -d -i -t centos:5 /bin/bash
2015/12/07 16:02:59 packer-builder-docker: 2015/12/07 16:02:59 Starting container with args: [run -v /var/folders/53/117c27k55hvgvcn0vt19kh2w0000gp/T/packer-docker206153419:/packer-files -d -i -t centos:5 /bin/bash]
2015/12/07 16:02:59 packer-builder-docker: 2015/12/07 16:02:59 Waiting for container to finish starting
2015/12/07 16:03:00 ui:     docker: Container ID: 01cf487ba76b681db3733bfe200b7002cbc16902792702723b48f073f0870e1c
    docker: Container ID: 01cf487ba76b681db3733bfe200b7002cbc16902792702723b48f073f0870e1c
2015/12/07 16:03:00 packer-builder-docker: 2015/12/07 16:03:00 Running the provision hook
2015/12/07 16:03:00 ui: ==> docker: Provisioning with shell script: /var/folders/53/117c27k55hvgvcn0vt19kh2w0000gp/T/packer-shell062583553
==> docker: Provisioning with shell script: /var/folders/53/117c27k55hvgvcn0vt19kh2w0000gp/T/packer-shell062583553
2015/12/07 16:03:00 packer-provisioner-shell: 2015/12/07 16:03:00 Opening /var/folders/53/117c27k55hvgvcn0vt19kh2w0000gp/T/packer-shell062583553 for reading
2015/12/07 16:03:00 packer-provisioner-shell: 2015/12/07 16:03:00 [INFO] 178 bytes written for 'uploadData'
2015/12/07 16:03:00 [INFO] 178 bytes written for 'uploadData'
2015/12/07 16:03:00 packer-builder-docker: 2015/12/07 16:03:00 Executing in container 01cf487ba76b681db3733bfe200b7002cbc16902792702723b48f073f0870e1c: "(command cp /packer-files/upload869619118 /tmp/script_7943.sh) >/packer-files/cmd013293365 2>&1; echo $? >/packer-files/cmd013293365-exit"
2015/12/07 16:03:02 packer-builder-docker: 2015/12/07 16:03:02 Waiting for exit code to appear for remote command...
```

**Comment by jstnlef** [comment]
I'd like to bump this. I'm seeing a very similar issue with the shell provisioner and docker builder.

**Comment by jstnlef** [comment]
Actually just went through the process of building from master branch and it looks like it worked fine for me.
```
Packer v0.8.7.dev (d507b18eb4cf00b7d832c8c3fc7bb46b6377b551)
```

**Comment by lv0** [comment]
After researching and building v0.8.7.dev (b7ba9a507d51820e40275faf8cc74af3267af535) 

i'm still seeing this issue when building from within a docker container... that is connecting to the parent docker daemon via exposed unix socket.

from builder.json

```
{
  "variables": {
    "imageTag": "",
    "imageRepo": ""
  },
  "builders": [
    {
      "type": "docker",
      "image": "ubuntu:latest",
      "commit": true,
      "run_command": [
        "-ti",
        "-v",
        "/tmp/packerfiles:/tmp/packerfiles",
        "-d",
        "{{.Image}}",
        "/bin/bash",
        "--noprofile",
        "--norc"
      ]
    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "scripts": [
        "packer/scripts/docker_ubuntu.sh"
      ]
    },
```

my packer invocation looks like this:

```
VERSION=$1
IMGREPO=$2
JSONFILE=$3
mkdir -p /tmp/packerfiles
TMPDIR=/tmp/packerfiles PACKER_LOG=1 packer build \
  -var imageTag=${VERSION} \
  -var imageRepo=${IMGREPO} \
  packer/scripts/${JSONFILE}.json
exit $?
```

output from `PACKER_LOG=1`
```
2016/01/22 18:45:44 ui: [1;32m==> docker: Starting docker container...[0m
2016/01/22 18:45:44 ui: [0;32m    docker: Run command: docker run -v /var/jenkins_home/.packer.d/tmp/packer-docker523294758:/packer-files -ti -v /tmp/packerfiles:/tmp/packerfiles -d ubuntu:latest /bin/bash --noprofile --norc[0m
[0;32m    docker: Status: Image is up to date for ubuntu:latest[0m
[1;32m==> docker: Starting docker container...[0m
2016/01/22 18:45:44 packer: 2016/01/22 18:45:44 Starting container with args: [run -v /var/jenkins_home/.packer.d/tmp/packer-docker523294758:/packer-files -ti -v /tmp/packerfiles:/tmp/packerfiles -d ubuntu:latest /bin/bash --noprofile --norc]
[0;32m    docker: Run command: docker run -v /var/jenkins_home/.packer.d/tmp/packer-docker523294758:/packer-files -ti -v /tmp/packerfiles:/tmp/packerfiles -d ubuntu:latest /bin/bash --noprofile --norc[0m
2016/01/22 18:45:44 packer: 2016/01/22 18:45:44 Waiting for container to finish starting
2016/01/22 18:45:47 ui: [0;32m    docker: Container ID: 6a9448c9580ac223dc4b8e5dbc7e174cc888293bf814e254cafe09c99dfe2570[0m
[0;32m    docker: Container ID: 6a9448c9580ac223dc4b8e5dbc7e174cc888293bf814e254cafe09c99dfe2570[0m
2016/01/22 18:45:47 packer: 2016/01/22 18:45:47 Running the provision hook
2016/01/22 18:45:47 ui: [1;32m==> docker: Provisioning with shell script: packer/scripts/docker_ubuntu.sh[0m
2016/01/22 18:45:47 packer: 2016/01/22 18:45:47 Opening packer/scripts/docker_ubuntu.sh for reading
[1;32m==> docker: Provisioning with shell script: packer/scripts/docker_ubuntu.sh[0m
2016/01/22 18:45:47 packer: 2016/01/22 18:45:47 [INFO] 1035 bytes written for 'uploadData'
2016/01/22 18:45:47 [INFO] 1035 bytes written for 'uploadData'
2016/01/22 18:45:47 packer: 2016/01/22 18:45:47 Executing in container 6a9448c9580ac223dc4b8e5dbc7e174cc888293bf814e254cafe09c99dfe2570: "(command cp /packer-files/upload507966797 /tmp/script_898.sh) >/packer-files/cmd213455432 2>&1; echo $? >/packer-files/cmd213455432-exit"
2016/01/22 18:45:49 packer: 2016/01/22 18:45:49 Waiting for exit code to appear for remote command...
```

I enter the container and inspect /packer-files

```
oot@docker3:~# docker exec -it big_kilby /bin/bash
root@6a9448c9580a:/# pushd /tmp/packerfiles/
/tmp/packerfiles /
root@6a9448c9580a:/tmp/packerfiles# ls -lah
total 16K
drwxr-xr-x 4 root root 4.0K Jan 22 18:35 .
drwxrwxrwt 3 root root 4.0K Jan 22 18:45 ..
drwxr-xr-x 2 root root 4.0K Jan 22 18:35 packer-docker329986877
drwxr-xr-x 2 root root 4.0K Jan 22 16:50 packer-docker463191192
root@6a9448c9580a:/tmp/packerfiles# cat packer-docker329986877/cmd749252215
cmd749252215       cmd749252215-exit
root@6a9448c9580a:/tmp/packerfiles# cat packer-docker329986877/cmd749252215*
cp: cannot stat '/packer-files/upload772259704': No such file or directory
1
root@6a9448c9580a:/tmp/packerfiles# pushd /packer-files/; ls -lah
/packer-files /tmp/packerfiles /
total 16K
drwxr-xr-x  2 root root 4.0K Jan 22 18:45 .
drwxr-xr-x 22 root root 4.0K Jan 22 18:45 ..
-rw-r--r--  1 root root   75 Jan 22 18:45 cmd213455432
-rw-r--r--  1 root root    2 Jan 22 18:45 cmd213455432-exit
root@6a9448c9580a:/packer-files# cat cmd213455432*
cp: cannot stat '/packer-files/upload507966797': No such file or directory
1
```
