### ISSUE TITLE
ami_users as array of strings

### ISSUE THREAD

**Issue by ExecPcs** [mitchellh/packer#3579]
- Packer v0.10.1
- CentOS Linux release 7.2.1511 (Core)
- [Log file](https://gist.github.com/ExecPcs/c0657f8c894313af904e4c8b9c24ea32)
- When im trying insert array of ami_users I get error "_\* variable ami_users: '' expected type 'string', got unconvertible type '[]interface {}'_"

**Comment by cbednarski** [comment]
Thanks for the report. This does not seem to be working as documented.

As a workaround you can try to specify this as a comma-delimited string, which I think will be converted into a list internally. Not sure if you'll run into the same problem, though, depending on where the type coercion is failing.

**Comment by ExecPcs** [comment]
With comma-delimited string working. Thanks!

**Comment by kwilczynski** [comment]
Easy to fix, I will have a look.

**Comment by madduci** [comment]
any news about this issue?

**Comment by rickard-von-essen** [comment]
This works as expected in 0.11.0.

**Comment by rickard-von-essen** [comment]
I can't find that this have been fixed and don't see that it have been broken in near time.

Please reopen if you can repro this with 0.11.0 and provide a full template to repro this.

**Comment by joshuaspence** [comment]
I think this problem still exists? Here is a template that can be used to reproduce:

```
{
  "variables": {
    "ami_users": []
  }
}
```

Running Packer on this template gives the following error:

```
Failed to parse template: 1 error(s) occurred:

* variable ami_users: '' expected type 'string', got unconvertible type '[]interface {}'
```

**Comment by rickard-von-essen** [comment]
@joshuaspence That's not the same error, and it's not a bug. All variables can't be arrays.

Try:

```json
{
  "variables": { "ami_users": "123456789012,987654321098" },
  "builders": [
     {
       "type": "amazon-ebs",
       "ami_users": "{{ user `ami_users` }}"
     }
  ]
}
```

**Comment by joshuaspence** [comment]
What do you mean? The error message I got is exactly as in the original report. I thought that this issue was regarding the ability to specify `ami_users` as an array rather than as a comma-separated list.

**Comment by rickard-von-essen** [comment]
Sorry read a bit to quickly, nevertheless you have the solution above.

**Comment by jakub-bochenski** [comment]
I'm confused. Can I use an array of strings for this attribute or not?
The docs specify `ami_users ([]string)` but it seems it doesn't work

**Comment by azr** [comment]
Hey @jakub-bochenski, yes, you can set it to `[]` or `["xxx", "xxx"]`.
